# -*- coding: utf-8 -*-

ids = {
    "alice coltrane": "0oKYiTD5CdNbrofRvM1dIr",
    "american football": "5FwydyGVcsQllnM4xM6jw4",
    "andrew bird's bowl of fire": "0Dan4711eVqYQnlUWfOvYN",
    "azizi gibson": "2NjfafEappzvGGGDdMRJMP",
    "black sabbath": "5M52tdBnJaKSvOpJGz8mfZ",
    "blonde redhead": "5isqImG0rLfAgBJSPMEVXF",
    "bob marley": "2QsynagSdAqZj3U9HgDzjD",
    "built to spill": "3kbBWco9PZ5eSQsNScwG6U",
    "chelsea wolfe": "6ZK2nrW8aCTg8Bid7I7N10",
    "cocteau twins": "5Wabl1lPdNOeIn0SQ5A1mp",
    "creedence clearwater revival": "3IYUhFvPQItj6xySrBmZkd",
    "daughters": "1LhK7wn59Hq6GNN4sUS3ih",
    "david bowie": "0oSGxfWSnnOXhD2fKuz2Gy",
    "death grips": "5RADpgYLOuS2ZxDq7ggYYH",
    "deerhoof": "7AZwAitWq1KcFoIJhRWb6V",
    "denzel curry": "6fxyWrfmjcbj5d12gXeiNV",
    "dirty three": "1QUsHFoDqNsC0W9AlNyHWF",
    "dr octagon": "7dr3cSEOIZ6tBrm4y1wsnr",
    "drive like jehu": "7FbdCzKUwoZs1v9bCl43Ev",
    "d'angelo": "336vr2M3Va0FjyvB55lJEd",
    "earl sweatshirt": "3A5tHz1SfngyOZM2gItYKu",
    "electric wizard": "4htjQW3lgIwL6fEJlTOez4",
    "erykah badu": "7IfculRW2WXyzNQ8djX8WX",
    "faust": "4yBBNmdvVaoPEnr2lt14q7",
    "fiona apple": "3g2kUQ6tHLLbmkV7T4GPtL",
    "fire orchestra": "50BFEG33gYorCS5zbNbLRb",
    "flatbush zombies": "1dqGS5sT6PE2wEvP1gROZC",
    "foxing": "2dfxY7YDuYCUtWFzWTS6IR",
    "flying lotus": "29XOeO6KIWxGthejQqn793",
    "gospel": "7uqOQ6QYdmLuF6NklBYdiY",
    "harvey milk": "0U06WlIl1leJMEHBf7WAwR",
    "have a nice life": "0FRKTwQSToXpCxYMhyUzYY",
    "hella": "1n861RIk6CTAWncgHR9UHg",
    "hiatus kaiyote": "43JlwunhXm1oqdKyOa2Z9Y",
    "iceage": "03hlOXqRyyXO3ectp3eEbU",
    "isis": "2vsXeWGC8rILp3rpSN2Fyk",
    "jambinai": "20xwrwSmGSBQLLV0EVRS9M",
    "james blake": "53KwLdlmrlCelAZMaLVZqU",
    "jimi hendrix": "776Uo845nYHJpNaStv1Ds4",
    "joey badass": "2P5sC9cVZDToPxyomzF1UH",
    "ka": "0cmqAB0gdr6ObvjNrQJAQr",
    "kamasi washington": "6HQYnRM4OzToCYPpVBInuU",
    "kendrick lamar": "2YZyLoL8N0Wb9xBt1NhZWg",
    "king crimson": "7M1FPw29m5FbicYzS2xdpi",
    "king krule": "4wyNyxs74Ux8UIDopNjIai",
    "larry young": "6Y6kAZs0W9NNsxNbpImPvq",
    "led zeppelin": "36QJpDe2go2KgaRleHCDTp",
    "liars": "2z78AlkdwE2Ghj9EB50M6z",
    "lightning bolt": "2og3FOCLYXT9H7IYE6QPUq",
    "little dragon": "6Tyzp9KzpiZ04DABQoedps",
    "magazine": "4VuMnSnoTGrma3a79UhfMs",
    "mammal hands": "497rp5TEzJffeBnUT0BeE1",
    "mariah": "0yMkwfeRG8lviQY0mZ1BBI",
    "mf doom": "2pAWfrd7WFF3XhVt9GooDL",
    "mia doi todd": "1r3efMZ0kcejkPKP8oQZzv",
    "miles davis": "0kbYTNQb4Pb1rPbbaF0pT4",
    "milo": "0J6PhnVD21GSFoJ9HoadLH",
    "modest mouse": "1yAwtBaoHLEDWAnWR87hBT",
    "moodie black": "3rd7jOmgOraHucrcvhYVy6",
    "moses sumney": "5W10uJRsbt9bROJDKoI1Wn",
    "mouse on the keys": "6NVzd3Lv9yMFIf1bsXNLIp",
    "nina simone": "7G1GBhoKtEPnP86X2PvEYO",
    "owls": "57sqenSxpn1IL2G0im58dj",
    "oxbow": "4m47y2u5lJBKbakAv5YAh1",
    "parquet courts": "23NIwARd4vPbxt3wwNnJ6k",
    "picastro": "1TTJJzHdc6IWChZrVpkr4k",
    "portishead": "6liAMWkVf5LH7YR9yfFy1Y",
    "pretend": "4rohfx5aI2ISAXUkFXPy9R",
    "radiohead": "4Z8W4fKeB5YxbusRsdQVPb",
    "rage against the machine": "2d0hyoQ5ynDBnkvAbJKORj",
    "robert johnson": "0f8MDDzIc6M4uH1xH0o0gy",
    "roberto musci": "1HSz5qiRNcs8eJ0Sp2LOxw",
    "rockets red glare": "0w0bmTGF2xge5DzAQQXj61",
    "ryuichi sakamoto": "1tcgfoMTT1szjUeaikxRjA",
    "sangre de muerdago": "31B0gbLzmTRdprWvyq5S2y",
    "seasick steve": "6OVkHZQP8QoBYqr1ejCGDv",
    "sheena ringo": "2XjqKvB2Xz9IdyjWPIHaXi",
    "slint": "4IwOItqRhsIoRuD5HP4vyC",
    "sons of kemet": "3pvRbmrqOyFxB2Eext4Dki",
    "stan getz": "0FMucZsEnCxs5pqBjHjIc8",
    "sturgill simpson": "3vDpQbGnzRbRVirXlfQagB",
    "sun ra": "0tIODqvzGUoEaK26rK4pvX",
    "swans": "79S80ZWgVhIPMCHuvl6SkA",
    "swell maps": "1FGzeqDPTLZwfbfxpmPAZn",
    "terry riley": "7DnLQaXsqcYkgm0nyDrB3r",
    "the avalanches": "3C8RpaI3Go0yFF9whvKoED",
    "the breeders": "1xgFexIwrf2QjbU0buCNnp",
    "the sea and cake": "0ihBDeJlIlXo4LFfAllsGm",
    "the upsetters": "12CNljuN6DW9e5x61FS03b",
    "thom yorke": "4CvTDPKA6W06DRfBnZKrau",
    "three 6 mafia": "26s8LSolLfCIY88ysQbIuT",
    "unwound": "4YjpqCSDD7zwMQgPYJMqb0",
    "vince staples": "68kEuyFKyqrdQQLLsmiatm",
    "wilco": "2QoU3awHVdcHS8LrZEKvSM",
    "wire": "2i8ynmFv4qgRksyDlBgi6d",
}
