[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "mmmusic"
version = "0.1.0"
description = "Tools for music discovery and managment"
authors = ["Mason Albright <14malbright@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"

[tool.autoflake]
exclude = ".venv"
ignore_init_module_imports = true
ignore_pass_after_docstring = true
in_place = true
recursive = true
remove_all_unused_imports = true
remove_duplicate_keys = true
remove_unused_variables = true

[tool.isort]
profile = "black"
force_sort_within_sections = true
honor_noqa = true
