[tool.autoflake]
exclude = ".venv"
ignore_init_module_imports = true
ignore_pass_after_docstring = true
in_place = true
recursive = true
remove_all_unused_imports = true
remove_duplicate_keys = true
remove_unused_variables = true

[tool.isort]
profile = "black"
force_sort_within_sections = true
honor_noqa = true
