name: Manage Q Playlists

on:
  workflow_dispatch:

env:
  SPOTIPY_CLIENT_ID: ${{ secrets.SPOTIPY_CLIENT_ID }}
  SPOTIPY_CLIENT_SECRET: ${{ secrets.SPOTIPY_CLIENT_SECRET }}
  SPOTIPY_CLIENT_USERNAME: ${{ secrets.SPOTIFY_USERNAME }}
  SPOTIPY_OPEN_BROWSER_FOR_OAUTH: false
  SPOTIPY_REDIRECT_URI: ${{ secrets.SPOTIPY_REDIRECT_URI }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install poetry
      run: pipx install poetry
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'poetry'
    - run: poetry install
    - name: Set up OAuth token cache
      run: |
        echo '${{ secrets.CACHED_TOKEN }}' > .cache-${{ secrets.SPOTIFY_USERNAME }}
    - name: Manage Q Playlists
      run: |
        poetry run python ./scripts/manage_q_playlists.py
